// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const gerRoom = `-- name: GerRoom :one
SELECT id, theme, name FROM rooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GerRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, gerRoom, id)
	var i Room
	err := row.Scan(&i.ID, &i.Theme, &i.Name)
	return i, err
}
